package ssh

import (
	"fmt"
	"freessh-backend/internal/keychain"
	"freessh-backend/internal/models"
	"strings"
	"time"

	"golang.org/x/crypto/ssh"
)

func ExportKeyToConnection(config models.ConnectionConfig, publicKey string, generatedPrivateKey string, keyName string) error {
	kc := keychain.New()
	clientConfig := &ssh.ClientConfig{
		User:            config.Username,
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		Timeout:         0,
	}

	// Get credentials from keychain
	if config.AuthMethod == "password" {
		password, err := kc.Get(config.ID)
		if err != nil || password == "" {
			return fmt.Errorf("password not found in keychain - please save connection credentials first")
		}
		clientConfig.Auth = []ssh.AuthMethod{
			ssh.Password(password),
		}
	} else if config.AuthMethod == "key" && config.PrivateKey != "" {
		passphrase, _ := kc.Get(config.ID + ":passphrase")
		
		var signer ssh.Signer
		var err error
		if passphrase != "" {
			signer, err = ssh.ParsePrivateKeyWithPassphrase([]byte(config.PrivateKey), []byte(passphrase))
		} else {
			signer, err = ssh.ParsePrivateKey([]byte(config.PrivateKey))
		}
		if err != nil {
			return fmt.Errorf("failed to parse private key: %w", err)
		}
		clientConfig.Auth = []ssh.AuthMethod{
			ssh.PublicKeys(signer),
		}
	} else {
		return fmt.Errorf("no valid authentication method configured for this connection")
	}

	addr := fmt.Sprintf("%s:%d", config.Host, config.Port)
	client, err := ssh.Dial("tcp", addr, clientConfig)
	if err != nil {
		return fmt.Errorf("failed to connect: %w", err)
	}
	defer client.Close()

	sshSession, err := client.NewSession()
	if err != nil {
		return fmt.Errorf("failed to create SSH session: %w", err)
	}
	defer sshSession.Close()

	// Format public key with comment and label
	timestamp := time.Now().Format("2006-01-02 15:04:05")
	comment := fmt.Sprintf("# Key added by FreeSSH - %s - %s", keyName, timestamp)
	keyWithLabel := strings.TrimSpace(publicKey) + " Generated By FreeSSH"
	
	// Append comment and key to authorized_keys
	cmd := fmt.Sprintf("mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo '%s' >> ~/.ssh/authorized_keys && echo '%s' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys", 
		comment, keyWithLabel)

	if err := sshSession.Run(cmd); err != nil {
		return fmt.Errorf("failed to export key: %w", err)
	}

	return nil
}
