package export

import (
	"fmt"
	"freessh-backend/internal/models"
	"strings"
)

func ExportOpenSSH(connections []models.ConnectionConfig, keyFileStorage KeyFileStorage) ([]byte, error) {
	var builder strings.Builder
	
	builder.WriteString("# FreeSSH OpenSSH Config Export\n")
	builder.WriteString("# Generated by FreeSSH\n\n")

	for _, conn := range connections {
		// Host alias (connection name)
		builder.WriteString(fmt.Sprintf("Host %s\n", sanitizeHostAlias(conn.Name)))
		
		// Hostname
		builder.WriteString(fmt.Sprintf("    HostName %s\n", conn.Host))
		
		// Port (only if not default 22)
		if conn.Port != 22 {
			builder.WriteString(fmt.Sprintf("    Port %d\n", conn.Port))
		}
		
		// User
		builder.WriteString(fmt.Sprintf("    User %s\n", conn.Username))
		
		// Identity file (if using key authentication)
		if conn.AuthMethod == models.AuthPublicKey && conn.KeyID != "" {
			// For OpenSSH export, we'll reference the key file path
			keyPath := fmt.Sprintf("~/.freessh/keys/%s.pem", conn.KeyID)
			builder.WriteString(fmt.Sprintf("    IdentityFile %s\n", keyPath))
		}
		
		builder.WriteString("\n")
	}

	return []byte(builder.String()), nil
}

// sanitizeHostAlias removes spaces and special characters from connection names
func sanitizeHostAlias(name string) string {
	// Replace spaces with hyphens
	name = strings.ReplaceAll(name, " ", "-")
	// Remove any other problematic characters
	name = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' || r == '.' {
			return r
		}
		return -1
	}, name)
	return name
}

type KeyFileStorage interface {
	GetPrivateKey(keyID string) (string, error)
}
